### ISSUE TITLE
Allow use of 3rd Party React Components

### ISSUE THREAD

**Issue by kRITZCREEK** [paf31/purescript-thermite#3]
A lot of React's philosophy is about the reusability of components. Enabling use of given React components written in Javascript would allow also allow partially porting a codebase to purescript. See eg, [React Bootstrap](http://react-bootstrap.github.io/)

**Comment by paf31** [comment]
@kRITZCREEK In 0.6.1, I've changed the old `Props` type to a type `Attr` which is closer to what React actually uses, so you should be able to get React Bootstrap working now, and I'll close this.

I've opened issue #25 to allow components to be embedded, which is the other part of the problem here.
