### ISSUE TITLE
React Mixins

### ISSUE THREAD

**Issue by kRITZCREEK** [paf31/purescript-thermite#6]
I was wondering if the Mixin concept of React can be translated to typeclasses in Thermite.

[The Documentation](http://facebook.github.io/react/docs/reusable-components.html#mixins) describes  a Mixin to be a set of shared functions across multiple different components. 

Could this be a way to write extensions to Thermite? I was especially thinking about a module that allows a component to produce its own Observable/Signal with purescript-rx / purescript-signal. Other common use cases would be adding Validation to Form Elements.

Maybe this route allows us to do something about #3 with some Javascript Magic. If you could point me into a direction I would love to go exploring and maybe provide a PR at the end.

**Comment by paf31** [comment]
I think that supporting mixins is a nice goal, but I'm not sure if I understand the connection to type classes. Could you give an example?

**Comment by kRITZCREEK** [comment]
I was thinking that a type class like Monad expects a user to implement the require methods bind and return.
If I now create eg. a Validatable extension and require "Validatable" components to have methods validates and showValidationError I could provide this typeclass along with some helper Methods for instances of Validatable. Could the *newtype Spec* constructor in Thermite.Types be a good spot to write up instances for?

**Comment by paf31** [comment]
I think it would be good to define a version without type classes first, and see if any obvious structure emerges. We could always build something with TCs on top, and a version based on records/ADTs should be pretty simple to add on.

**Comment by rtrvrtg** [comment]
Hi,

This is exactly the sort of thing that I'm interested in using, because I'd like to be able to use some of the mixins out there that handle things like saving the current app state to localStorage, path routing and so on.

I've forked purescript-thermite and started to work on porting this, but I don't think I know enough about PureScript to get this working as is.

Here's the new definition of the Spec type: https://github.com/rtrvrtg/purescript-thermite/blob/wip-foreign-spec/src/Thermite/Types.purs (with four arguments to handle `m state props action`)
The initial invocation from a SpecRecord, and methods to change `componentWillMount` and `displayName`: https://github.com/rtrvrtg/purescript-thermite/blob/wip-foreign-spec/src/Thermite.purs

However, right now it's failing to build due to an issue in `Thermite.Internal`:
```text
Compiling Thermite.Internal
Error at src/Thermite/Internal.purs line 72, column 1 - line 104, column 1: 
Error in foreign import declaration createClassImpl
Cannot unify * -> * with *.
* ERROR: Subcommand terminated with error code 1
```

I suspect it's not liking how I'm attempting to reuse the redefined Spec type here. Not quite sure what to do about it, though – might go off and do some tests with types like this on my own before I try this again.

**Comment by paf31** [comment]
@rtrvrtg The kind of `Spec` hasn't changed, I think. Also, we use record updates rather than direct mutation because we want to avoid the side-effect of mutation. Record updates create a fresh record with the updated fields.

**Comment by felixSchl** [comment]
Any movement on this? I am just getting into React, but Mixins seem to play an important role in the plugin space, e.g. I was just looking at [yahoo/react-intl](https://github.com/yahoo/react-intl), but cannot use it as it stands.

**Comment by paf31** [comment]
In 0.11, this will be much simpler since you can just create a `ReactSpec` for your Thermite component, and add the mixin there.

**Comment by paf31** [comment]
Closing this, since 0.11 has supported addons like this via `purescript-react` types.
