### ISSUE TITLE
Two state updates (cotransforms) in one performAction

### ISSUE THREAD

**Issue by asvyazin** [paf31/purescript-thermite#65]
In some cases two cotransforms in one performAction don't work, second is just ignored

For example insert `T.cotransform id` into `ChangeCompleted` action handler in test/Components/Task.purs:
```purescript
  performAction (ChangeCompleted b)   _ _ = do
    T.cotransform id
    void (T.cotransform (_ { completed = b }))
```

And btw two cotransforms work fine in TaskList handlers

**Comment by asvyazin** [comment]
There is another problem now... Now UI "waits" for final `cotransform` to re-render. Let's say you have something like:
```purescript
performAction SomethingHappened _ _ = do
  T.cotransform $ \s -> s { showLoader = true }
  lift longAjaxRequest
  void $ T.cotransform $ \s -> s { showLoader = false }
```
then loader will not be shown at all. Should I start another issue?

**Comment by paf31** [comment]
Thanks for pointing this out. This might be due to a problem in `coroutines` actually. We had a similar problem with producers and consumers at one point.

I'll have a look soon, but if you need a solution now, you might want to try switching around the order of the arguments to `transformCoTransform`.

**Comment by paf31** [comment]
This is fixed by https://github.com/purescript-contrib/purescript-coroutines/pull/12

**Comment by paf31** [comment]
This is fixed in master now.
