### ISSUE TITLE
Monolithic components

### ISSUE THREAD

**Issue by BartAdv** [paf31/purescript-thermite#77]
Would it be feasible (unless it's design decision), for the Spec combining to somehow retain the components hierarchy (that is, not resulting in one monolithic component)?

That is, for example with `focus`:

```purescript
spec1 :: Spec _ S1 _ A1
spec2 :: Spec _ S2 _ A2

spec :: Spec _ (Tuple S1 S2) _ (Either A1 A2)
spec = focus _1 _Left spec1 <> focus _2 _Right spec2
```

In my opinion, this should ideally result in a component having `Tuple S1 S2` as state, passing `S1` to 'left' component, `S2` to 'right' component (as props), and the dispatch would left as it is (I think).

Now, why it should be done?

* performance - I haven't measured it with Thermite, but I worked with an application where big component was resulting in bad performance. Sure there's virtual dom diffing, but the virtual copy of that DOM has to be rendered as a whole, whereas with smaller components one could use `shouldComponentUpdate` (and I believe it could be great with immutable data structures) to just optimize it out

* tooling - Chrome' DevTools would probably offer better inspectability

**Comment by paf31** [comment]
> and the dispatch would left as it is

This is the part I don't understand.

We could implement something like what you're suggesting, but it would be a very different design from what's here now - so much so that I think it would be a separate library entirely. I think you might want to look at Halogen instead. Halogen does diffing per-component as I understand it.
